name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (JS)
        run: npm run lint:js

      - name: Run Stylelint (CSS)
        run: npm run lint:css

      - name: Run HTMLHint (HTML)
        run: npm run lint:html

      - name: Check formatting
        run: npm run format:check
